# Generated by Django 5.2.4 on 2025-07-30 19:50

from django.db import migrations

def seed_recipes(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Recipe = apps.get_model('application', 'Recipe')
    Tag = apps.get_model('application', 'Tag')
    RecipeTag = apps.get_model('application', 'RecipeTag')

    try:
        author = User.objects.get(username='chefupteam')
    except User.DoesNotExist:
        return

    recipe_data = [
        {
            "title": "Spaghetti Aglio e Olio",
            "description": "A simple and flavorful Italian pasta with garlic and olive oil.",
            "ingredients": "200g spaghetti\n4 cloves garlic, sliced\n1/4 cup olive oil\n1 tsp red pepper flakes\nSalt to taste\nFresh parsley, chopped",
            "instructions": "1. Cook spaghetti until al dente.\n2. In a pan, heat olive oil and sauté garlic until golden.\n3. Add red pepper flakes and cooked spaghetti.\n4. Toss with parsley and serve hot.",
            "tags": ["italian", "quick", "vegetarian"]
        },
        {
            "title": "Chocolate Chip Cookies",
            "description": "Classic soft and chewy cookies packed with chocolate chips.",
            "ingredients": "2 1/4 cups flour\n1 tsp baking soda\n1 tsp salt\n1 cup butter\n3/4 cup sugar\n3/4 cup brown sugar\n1 tsp vanilla\n2 eggs\n2 cups chocolate chips",
            "instructions": "1. Preheat oven to 375°F.\n2. Cream butter and sugars. Add eggs and vanilla.\n3. Mix in dry ingredients and chocolate chips.\n4. Scoop onto tray and bake for 10–12 mins.",
            "tags": ["dessert", "baked", "easy"]
        },
        {
            "title": "Avocado Toast",
            "description": "Healthy and easy breakfast with mashed avocado on toasted bread.",
            "ingredients": "2 slices sourdough bread\n1 avocado\n1/2 lemon, juiced\nSalt and pepper\nChili flakes (optional)",
            "instructions": "1. Toast the bread.\n2. Mash avocado with lemon juice, salt, and pepper.\n3. Spread on toast and top with chili flakes.",
            "tags": ["breakfast", "vegan", "under-30-min"]
        },
        {
            "title": "Grilled Cheese Sandwich",
            "description": "Golden grilled sandwich with gooey melted cheese.",
            "ingredients": "2 slices white bread\n2 slices cheddar cheese\n1 tbsp butter",
            "instructions": "1. Heat skillet over medium heat.\n2. Butter bread and place cheese between slices.\n3. Grill until golden brown on both sides.",
            "tags": ["lunch", "easy", "weeknight"]
        },
        {
            "title": "Caesar Salad",
            "description": "Crisp romaine lettuce tossed in Caesar dressing and topped with croutons and Parmesan.",
            "ingredients": "1 head romaine lettuce\n1/2 cup croutons\n1/4 cup grated Parmesan\nCaesar dressing",
            "instructions": "1. Chop lettuce.\n2. Toss with dressing, croutons, and Parmesan.\n3. Serve immediately.",
            "tags": ["lunch", "under-30-min", "mediterranean"]
        },
        {
            "title": "Blueberry Smoothie",
            "description": "Refreshing smoothie made with blueberries, banana, and yogurt.",
            "ingredients": "1 cup blueberries\n1 banana\n1/2 cup yogurt\n1/2 cup milk\n1 tsp honey",
            "instructions": "1. Combine all ingredients in blender.\n2. Blend until smooth.\n3. Serve chilled.",
            "tags": ["breakfast", "under-30-min", "no-cook"]
        },
        {
            "title": "Veggie Stir Fry",
            "description": "Colorful medley of vegetables stir-fried in a savory soy-based sauce.",
            "ingredients": "1 bell pepper\n1 cup broccoli\n1 carrot\n2 tbsp soy sauce\n1 tbsp sesame oil\nGarlic and ginger",
            "instructions": "1. Heat oil in pan.\n2. Add garlic, ginger, and veggies.\n3. Stir-fry for 5–7 mins.\n4. Add soy sauce and serve.",
            "tags": ["dinner", "vegan", "quick"]
        },
        {
            "title": "Chicken Tikka Masala",
            "description": "Creamy tomato-based curry with marinated grilled chicken.",
            "ingredients": "2 chicken breasts\n1/2 cup yogurt\n2 tsp garam masala\n1 tsp paprika\n1 cup tomato puree\n1/2 cup cream",
            "instructions": "1. Marinate chicken in yogurt and spices.\n2. Grill or sauté.\n3. Simmer tomato sauce with cream and add chicken.",
            "tags": ["indian", "dinner", "grilled"]
        },
        {
            "title": "Pancakes",
            "description": "Fluffy breakfast pancakes served with syrup.",
            "ingredients": "1 cup flour\n2 tbsp sugar\n1 tsp baking powder\n1 egg\n1 cup milk\n2 tbsp butter",
            "instructions": "1. Mix dry ingredients.\n2. Whisk in egg, milk, and melted butter.\n3. Cook on griddle until bubbles form, flip, and cook other side.",
            "tags": ["breakfast", "dessert", "easy"]
        }
    ]

    for entry in recipe_data:
        recipe = Recipe.objects.create(
            title=entry["title"],
            description=entry["description"],
            ingredients=entry["ingredients"],
            instructions=entry["instructions"],
            author=author,
            is_public=True
        )
        for tag_name in entry["tags"]:
            try:
                tag = Tag.objects.get(name=tag_name)
                RecipeTag.objects.create(recipe=recipe, tag=tag)
            except Tag.DoesNotExist:
                pass  

def unseed_recipes(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Recipe = apps.get_model('application', 'Recipe')

    try:
        author = User.objects.get(username='chefupteam')
    except User.DoesNotExist:
        return

    Recipe.objects.filter(author=author).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_seed_premade_tags'),
    ]

    operations = [
        migrations.RunPython(seed_recipes, reverse_code=unseed_recipes),
    ]
